// Every string Pilo writes for itself lives here. Requests, reports and replies
// are the user's own words and never pass through this file.
//
// English is what ships; PILO_LANG=ko switches the whole surface. Keys are
// grouped by where they appear, and a missing key falls back to English rather
// than to nothing.
const EN = {
  // status words in the agent tree
  "state.idle": "idle",
  "state.running": "running",
  "state.stalled": "stalled",
  "state.blocked": "blocked",
  "state.failed": "failed",
  "state.unbound": "unbound",
  "state.gaveUp": "no answer",
  "state.holding": "holding",
  "state.limited": "limited",

  // the tree itself
  "tree.title": "AGENT TREE",
  "tree.noDesk": "no desk agent",
  "tree.noPm": "no project agents — register in :dash",
  "tree.register": "register agent - :dash agents",
  "tree.sessionOff": "session not bound",
  "tree.sessionQuiet": "quiet",
  "tree.sessionBusy": "running",
  "tree.sessionGone": "session lost",

  // request cards
  "card.replyBadge": "FINAL_REPLY",
  "card.replyFooter": "run log · changed files · artifacts in :dash",
  "card.needsReply": "writing reply",
  "card.needsReplyOne": "all tasks done · waiting on the reply",
  "card.needsReplyMany": "{count} results in · waiting on one reply",
  "card.waiting": "working · waiting on the result",
  "card.queued": "received · the desk agent is looking",

  // the feed and the prompt
  "feed.empty": "type an instruction below.",
  "feed.emptyFiltered": "nothing for {project}",
  "feed.older": "↑ {count} lines above · PgUp/⇧↑",
  "feed.scrolled": "↑ {count} lines up · PgDn/⇧↓ for the latest",
  "feed.placeholder": "ask anything  ·  :dash for the dashboard",
  "feed.filter": "filter: {project} · click PILO or :project all to clear",
  "header.help": ":help — commands",

  // notes the TUI writes back
  "note.filterOn": "filter: {project}",
  "note.filterOff": "filter cleared — all requests",
  "note.noAgents": "no agents registered. add one in :dash agents.",
  "note.copied": "copied {what}",
  "note.nothingToCopy": "nothing to copy",
  "note.copyUsage": "usage: :copy [last | in-65 | task-389 | draft]",
  "note.noClipboardImage": "no image on the clipboard",
  "note.pasteKeyUnread": "that paste key came in from another input source and could not be read — switch to English input, or press Ctrl+V",
  "note.attached": "attached {what}",
  "note.iconsOn": "runtime icons on — needs an icon font (Nerd Fonts 3.5.0 or newer)",
  "note.iconsOff": "runtime icons off — three-letter labels instead",
  "note.noSchedules": "no schedules — add one with pilo api POST /api/schedules",
  "note.scheduleUsage": "usage: :schedule <id> on|off|rm",
  "note.scheduleOn": "schedule {id} on",
  "note.scheduleOff": "schedule {id} off — it will not fire again until you turn it on",
  "note.scheduleRemoved": "schedule {id} deleted",
  "note.scheduleFailed": "could not change schedule {id}",
  "note.mouseOn": "mouse on — wheel scrolls, click selects",
  "note.mouseOff": "mouse off — drag to select as usual. PgUp/PgDn scrolls; :mouse to undo",
  "note.dashOpened": "opened the dashboard",
  "note.agentsTab": "opened the dashboard's Agents tab",
  "note.unknown": "unknown command: :{word} — see :help",
  "note.didYouMean": "unknown command. did you mean {names}?",
  "note.sendFailed": "could not save the request: {reason}",
  "note.projects": "projects: {list}   filter: {current}   (:project <name> · :project all)",
  "note.none": "none",
  "note.all": "all",
  "note.noBlocked": "nothing waiting on a decision",
  "note.answered": "answered #{id} — the agent is being woken",
  "note.answerUsage": 'usage: :answer <taskId> <answer>',

  // setup screen
  "setup.title": "setup required",
  "setup.lead": "what Pilo needs to start. one command, `pilo up`; agents are registered in the dashboard.",
  "setup.duplicate": "{count} agents claim role=pilo",
  "setup.duplicateHint": "there must be exactly one. remove the others in the dashboard.",
  "setup.herdr": "herdr running",
  "setup.herdrOk": "{count} agent sessions found",
  "setup.herdrHint": "start herdr first, or agents have nothing to attach to",
  "setup.postgres": "Database ready",
  "setup.postgresOk": "PGlite with pgvector · ~/.pilo/data",
  "setup.desk": "desk agent registered (role=pilo)",
  "setup.deskOk": "one agent to talk to",
  "setup.pm": "PM agents (optional)",
  "setup.pmOk": "Pilo works with the desk agent alone",
  "setup.register": "dashboard → Agents → register agent",
  "setup.open": "open the dashboard with :dash to register.",

  // CLI
  "cli.inboxEmpty": "inbox is empty",
  "cli.noAgents": "no agents registered",
  "cli.taskSent": "task #{id} → agent {agent}",
  "cli.replySaved": "final_reply #{id} saved (in-{inbox})",
  "cli.progressSaved": "task #{id} progress: {text}",
  "cli.result": "task #{id} {status}",
  "cli.holding": "#{id} holding — {note}",
  "cli.resumed": "#{id} back in the queue",
  "cli.limited": "waking paused until {until}",
  "cli.unlimited": "limit cleared — waking again",
  "cli.blocked": "task #{id} {status} — waiting on the user",
  "cli.noBlocked": "nothing waiting on a decision",
  "cli.answered": "task #{id} {status} — waking the agent",
  "cli.asked": "said to the user in in-{inbox} — their reply goes to task #{id}",
  "event.asked": "desk asked the user about #{id}",
  "event.reminded": "still waiting on you — #{id} · {agent}",
  "wake.blocked": "[pilo:blocked] task #{id} in request #{inbox} is waiting on the user — read it with 'pilo inbox {inbox}', then tell them with 'pilo ask {id} \"…\"'.",
  "card.decision": "needs your decision",
  "card.decisionFooter": "click to answer here · or :answer {id} …",
  "card.decisionMore": "+{count} more waiting in this request",
  "feed.answering": "answering task #{id} — Enter sends · Esc cancels",
  "note.answering": "answering task #{id} — type below",
  "desk.decision.who": "{agent} · needs your decision · task #{id}",
  "desk.decision.done": "{agent} · decision answered · task #{id}",
  "desk.decision.answer": "Answer",
  "desk.decision.chip": "answering task #{id}",
  "cli.replyAttached": " · results from {agents} attached",
  "cli.historyNone": "nothing found for \"{words}\"",
  "cli.historyMore": "{count} shown and there are more — narrow with --since or another word · whole text: pilo inbox N",
  "cli.historyEnd": "whole text: pilo inbox N",
  "history.request": "request",
  "history.reply": "answer",
  "history.result": "result",
  "history.instruction": "task",
  "reply.failed": "failed",
  "reply.nothingToAttach": "in-{id} has no finished results to attach — write the answer out and save it with plain pilo reply",

  // events
  "event.woken": "{agent} woken",
  "event.wakeFailed": "wake failed — {code}",
  "event.opened": "{agent} opened #{id}",
  "event.holding": "#{id} is holding — waiting on something outside Pilo",
  "event.resumed": "#{id} is back in the queue",
  "event.limited": "{agent} hit its usage limit",
  "event.parked": "{agent} is limited — the wake waits",
  "event.unlimited": "{agent} is off the limit",
  "event.coalesced": "{agent} already had a wake waiting",
  "event.suppressed": "{agent} is over {cap} wakes this hour — the work stays queued",
  "event.stalled": "#{id} has not moved",
  "event.gaveUp": "{agent} not answering — stopped retrying",
  "event.registered": "{agent} registered",
  "event.archived": "{agent} archived",
  "event.rebound": "{agent} rebound",
  "event.rulesWritten": "{agent} instructions {action}",
  "event.rulesCreated": "written",
  "event.rulesUpdated": "updated",
  "event.rulesBroadcast": "{reason} — instructions reissued for {count}",
  "event.blocked": "{agent} waiting on a decision #{id}",
  "event.answered": "{agent} decision returned #{id}",
  "event.progress": "{agent} progress #{id}",
  "event.dismissed": "{agent} wake failures dismissed",
  "event.probeLost": "usage probe pane {pane} is gone — the usage figure will go stale until it is back",

  // wake messages, which the instruction files quote verbatim
  "wake.inbox": "[pilo:inbox] request #{id} — for {agent}. read it with 'pilo inbox {id}'.",
  "wake.task": "[pilo:task] task #{id} — for {agent}. read it with 'pilo task {id}', report with 'pilo done {id}'.",
  "wake.answer": "[pilo:task] decision returned #{id} — for {agent}. read the answer in 'pilo task {id}' and carry on.",
  "wake.nudge": "[pilo:nudge] task #{id} — for {agent}. still open, nothing reported. finish it, or report it with 'pilo done {id}'.",
  "wake.result": "[pilo:result] results in for #{id} — gather them with 'pilo inbox {id}', then 'pilo reply {id}'.",
  "wake.rules": "[pilo:rules] your instructions changed. read the pilo:begin ~ pilo:end block in {file} and follow it from now on.",
  "wake.check": "[pilo] {agent}, please check in",

  // dashboard chrome
  "dash.tab.work": "Work",
  "dash.tab.work.desc": "the tree, the conversation, and the line you type",
  "dash.tab.overview": "Overview",
  "dash.tab.overview.desc": "agent state · recent tasks · runtime",
  "dash.tab.agents": "Agents",
  "dash.tab.agents.desc": "the tree, and where agents are registered",
  "dash.tab.inbox": "Inbox",
  "dash.tab.inbox.desc": "what was asked, and how it was handled",
  "dash.tab.events": "Events",
  "dash.tab.events.desc": "pm_result · final_reply · raw events",
  "dash.tab.artifacts": "Artifacts",
  "dash.tab.artifacts.desc": "files the agents changed",
  "dash.tab.projects": "Projects",
  "dash.tab.projects.desc": "projects, their paths, and who owns them",
  "dash.tab.schedules": "Schedules",
  "dash.tab.schedules.desc": "standing jobs · what fires when",
  "dash.tab.commands": "Commands",
  "dash.tab.commands.desc": "what you can type, in the TUI and the CLI",
  "dash.tab.settings": "Settings",
  "dash.tab.settings.desc": "notifications · tokens · retention",
  "dash.tab.system": "System",
  "dash.tab.system.desc": "server · wake · dashboard state and paths",

  // the desk screens. The rest of the dashboard's wording is the design's own
  // English and does not switch yet.
  "desk.rail.work": "work",
  "desk.rail.agents": "agents",
  "desk.rail.inbox": "requests",
  "desk.rail.schedules": "schedules",
  "desk.rail.events": "events",
  "desk.rail.artifacts": "artifacts",
  "desk.rail.projects": "projects",
  "desk.rail.commands": "commands",
  "desk.rail.settings": "settings",
  "desk.rail.system": "system",
  "desk.title.agents": "Agents",
  "desk.title.inbox": "Requests",
  "desk.title.schedules": "Schedules",
  "desk.title.events": "Events",
  "desk.title.artifacts": "Artifacts",
  "desk.title.projects": "Projects",
  "desk.title.commands": "Commands",
  "desk.title.settings": "Settings",
  "desk.title.system": "System",
  "desk.act.addAgent": "Add agent",
  "desk.act.resendRules": "Re-send rules",
  "desk.act.newSchedule": "New schedule",
  "desk.act.newProject": "New project",
  "desk.act.save": "Save",
  "desk.act.remove": "Remove",
  "desk.act.cancel": "Cancel",
  "desk.act.wake": "Wake",
  "desk.act.bind": "Bind again",
  "desk.act.copy": "Copy",
  "desk.act.close": "Close",
  "desk.lbl.byAgent": "by agent",
  "desk.lbl.requests": "requests",
  "desk.lbl.handling": "handling",
  "desk.lbl.everyAgent": "every agent",
  "desk.lbl.files": "files",
  "desk.lbl.eventLog": "event log",
  "desk.lbl.recentRuns": "recent runs",
  "desk.lbl.appearance": "appearance",
  "desk.lbl.services": "services",
  "desk.lbl.sessions": "herdr sessions",
  "desk.lbl.tokensToday": "tokens today",
  "desk.lbl.wakeFailures": "wake failures",
  "desk.lbl.paths": "paths",
  "desk.lbl.log": "log",
  "desk.lbl.language": "Language",
  "desk.lbl.theme": "Theme",
  "desk.lbl.nothingHere": "nothing here",
  "desk.lbl.clearFilter": "Clear filter",
  "desk.composer": "Type what you want done",
  "desk.composer.hint": "ENTER to send",
  "desk.follow.ask": "follow up",
  "desk.follow.chip": "follow-up to in-{id}",
  "desk.follow.cancel": "don't follow up",
  "desk.follow.prefix": "follow-up to in-{id} — "
};

const KO = {
  "state.idle": "대기",
  "state.running": "작업 중",
  "state.stalled": "멈춘 듯",
  "state.blocked": "결정 대기",
  "state.failed": "실패",
  "state.unbound": "세션 없음",
  "state.gaveUp": "응답 없음",
  "state.holding": "보류",
  "state.limited": "한도",

  "tree.title": "AGENT TREE",
  "tree.noDesk": "대표 agent 없음",
  "tree.noPm": "project agent 없음 — :dash 에서 등록",
  "tree.register": "register agent - :dash agents",
  "tree.sessionOff": "세션 미연결",
  "tree.sessionQuiet": "대기",
  "tree.sessionBusy": "실행 중",
  "tree.sessionGone": "세션 끊김",

  "card.replyBadge": "FINAL_REPLY",
  "card.replyFooter": "실행 로그 · 변경 파일 · 아티팩트는 :dash",
  "card.needsReply": "답변 작성 중",
  "card.needsReplyOne": "작업 완료 · 최종 답변 대기",
  "card.needsReplyMany": "결과 {count}건 도착 · 최종 답변 대기",
  "card.waiting": "작업 중 · 결과 대기",
  "card.queued": "요청 접수 · 대표 agent 확인 중",

  "feed.empty": "아래 프롬프트에 지시를 입력하세요.",
  "feed.emptyFiltered": "{project} 요청 없음",
  "feed.older": "↑ 이전 기록 {count}줄 · PgUp/⇧↑",
  "feed.scrolled": "↑ 위로 {count}줄 · PgDn/⇧↓ 로 최근으로",
  "feed.placeholder": "무엇이든 물어보세요  ·  :dash 로 대시보드",
  "feed.filter": "필터: {project} · PILO 클릭 또는 :project all 로 해제",
  "header.help": ":help — 명령",

  "note.filterOn": "필터: {project}",
  "note.filterOff": "필터 해제 — 전체 요청 표시",
  "note.noAgents": "등록된 agent가 없습니다. :dash agents 에서 등록하세요.",
  "note.copied": "{what} 복사됨",
  "note.nothingToCopy": "복사할 내용 없음",
  "note.copyUsage": "사용법: :copy [last | in-65 | task-389 | draft]",
  "note.noClipboardImage": "클립보드에 이미지 없음",
  "note.pasteKeyUnread": "다른 입력 소스에서 눌린 붙여넣기 키라 읽지 못함 — 영문 입력으로 바꾸거나 Ctrl+V",
  "note.attached": "{what} 첨부됨",
  "note.iconsOn": "runtime 아이콘 켜짐 — 아이콘 폰트 필요(Nerd Fonts 3.5.0 이상)",
  "note.iconsOff": "runtime 아이콘 꺼짐 — 세 글자 라벨로 표시",
  "note.noSchedules": "예약 없음 — pilo api POST /api/schedules 로 등록",
  "note.scheduleUsage": "사용법: :schedule <id> on|off|rm",
  "note.scheduleOn": "예약 {id} 켬",
  "note.scheduleOff": "예약 {id} 끔 — 다시 켤 때까지 안 돎",
  "note.scheduleRemoved": "예약 {id} 삭제",
  "note.scheduleFailed": "예약 {id} 변경 실패",
  "note.mouseOn": "마우스 켜짐 — 휠 스크롤, 클릭 선택",
  "note.mouseOff": "마우스 꺼짐 — 드래그로 복사. 스크롤은 PgUp/PgDn, 되돌리려면 :mouse",
  "note.dashOpened": "대시보드를 열었습니다",
  "note.agentsTab": "대시보드 Agents 탭을 열었습니다",
  "note.unknown": "알 수 없는 명령: :{word} — :help 참고",
  "note.didYouMean": "알 수 없는 명령입니다. 혹시 {names}?",
  "note.sendFailed": "요청 저장 실패: {reason}",
  "note.projects": "프로젝트: {list}   현재 필터: {current}   (:project <이름> · :project all)",
  "note.none": "없음",
  "note.all": "전체",
  "note.noBlocked": "결정 대기 중인 작업 없음",
  "note.answered": "#{id} 회신 저장 — agent를 깨웁니다",
  "note.answerUsage": "사용법: :answer <taskId> <답변>",

  "setup.title": "설정이 필요합니다",
  "setup.lead": "기동에 필요한 항목입니다. 명령은 `pilo up` 하나뿐이고, agent 등록은 대시보드에서 합니다.",
  "setup.duplicate": "role=pilo agent가 {count}개 감지됨",
  "setup.duplicateHint": "대표 agent는 정확히 하나여야 합니다. 대시보드에서 하나만 남기세요.",
  "setup.herdr": "herdr 실행 중",
  "setup.herdrOk": "agent 세션 {count}개 감지됨",
  "setup.herdrHint": "herdr를 먼저 띄워야 agent를 붙일 수 있습니다",
  "setup.postgres": "데이터베이스 준비",
  "setup.postgresOk": "PGlite · pgvector · ~/.pilo/data",
  "setup.desk": "대표 agent 등록 (role=pilo)",
  "setup.deskOk": "사용자와 대화할 agent 1개",
  "setup.pm": "PM agent 등록 (선택)",
  "setup.pmOk": "PM이 없어도 대표 agent와 대화는 가능합니다",
  "setup.register": "dashboard → Agents → register agent",
  "setup.open": ":dash 로 대시보드를 열어 등록하세요.",

  "cli.inboxEmpty": "inbox 비어 있음",
  "cli.noAgents": "등록된 agent 없음",
  "cli.taskSent": "task #{id} → agent {agent}",
  "cli.replySaved": "final_reply #{id} 저장됨 (in-{inbox})",
  "cli.progressSaved": "task #{id} 진행: {text}",
  "cli.result": "task #{id} {status}",
  "cli.holding": "#{id} 보류 — {note}",
  "cli.resumed": "#{id} 다시 대기열로",
  "cli.limited": "{until} 까지 깨우기 멈춤",
  "cli.unlimited": "한도 해제 — 다시 깨움",
  "cli.blocked": "task #{id} {status} — 사용자 결정 대기",
  "cli.noBlocked": "결정 대기 중인 작업 없음",
  "cli.answered": "task #{id} {status} — agent 를 다시 깨웁니다",
  "cli.asked": "in-{inbox} 대화에 사용자에게 말함 — 답은 task #{id} 로 감",
  "event.asked": "데스크가 #{id} 결정을 사용자에게 물음",
  "event.reminded": "아직 결정 대기 — #{id} · {agent}",
  "wake.blocked": "[pilo:blocked] 요청 #{inbox} 의 작업 #{id} 가 사용자 결정 대기 — 'pilo inbox {inbox}' 로 읽고 'pilo ask {id} \"…\"' 로 사용자에게 말할 것.",
  "card.decision": "결정이 필요해요",
  "card.decisionFooter": "클릭해서 여기서 답하기 · 또는 :answer {id} …",
  "card.decisionMore": "이 요청에 {count}건 더 기다리는 중",
  "feed.answering": "작업 #{id} 에 답하는 중 — Enter 보내기 · Esc 취소",
  "note.answering": "작업 #{id} 에 답하기 — 아래에 입력",
  "desk.decision.who": "{agent} · 결정 필요 · task #{id}",
  "desk.decision.done": "{agent} · 결정 답함 · task #{id}",
  "desk.decision.answer": "답하기",
  "desk.decision.chip": "task #{id} 에 답하는 중",
  "cli.replyAttached": " · {agents} 결과 붙임",
  "cli.historyNone": "\"{words}\" 로 찾은 기록 없음",
  "cli.historyMore": "{count}건 표시, 더 있음 — --since 나 단어를 더해 좁히기 · 전문은 pilo inbox N",
  "cli.historyEnd": "전문은 pilo inbox N",
  "history.request": "요청",
  "history.reply": "답",
  "history.result": "결과",
  "history.instruction": "지시",
  "reply.failed": "실패",
  "reply.nothingToAttach": "in-{id} 에 붙일 완료 결과 없음 — 답을 직접 써서 pilo reply 로 저장",

  "event.woken": "{agent} 깨움",
  "event.wakeFailed": "wake 실패 — {code}",
  "event.opened": "{agent} 가 #{id} 를 열어봄",
  "event.holding": "#{id} 보류 — 바깥 일을 기다리는 중",
  "event.resumed": "#{id} 다시 대기열로",
  "event.limited": "{agent} 사용량 한도에 걸림",
  "event.parked": "{agent} 한도 중 — 깨우기 보류",
  "event.unlimited": "{agent} 한도 풀림",
  "event.coalesced": "{agent} 는 이미 깨우기가 대기 중",
  "event.suppressed": "{agent} 시간당 {cap}회 넘음 — 일감은 그대로 남음",
  "event.stalled": "#{id} 가 안 움직임",
  "event.gaveUp": "{agent} 응답 없음 — 재알림 중단",
  "event.registered": "{agent} 등록",
  "event.archived": "{agent} 보관",
  "event.rebound": "{agent} 세션 재연결",
  "event.rulesWritten": "{agent} 지시문 {action}",
  "event.rulesCreated": "생성",
  "event.rulesUpdated": "갱신",
  "event.rulesBroadcast": "{reason} — 지시문 {count}건 재발행",
  "event.blocked": "{agent} 결정 대기 #{id}",
  "event.answered": "{agent} 결정 회신 #{id}",
  "event.progress": "{agent} 진행 #{id}",
  "event.dismissed": "{agent} wake 실패 확인 처리",
  "event.probeLost": "사용량 probe 창 {pane} 이 사라짐 — 다시 붙이기 전까지 사용량 값이 낡아감",

  "wake.inbox": "[pilo:inbox] 요청 도착 #{id} — {agent} 앞. 'pilo inbox {id}' 로 확인.",
  "wake.task": "[pilo:task] 작업 도착 #{id} — {agent} 앞. 'pilo task {id}' 로 읽고 'pilo done {id}' 로 보고.",
  "wake.answer": "[pilo:task] 결정 회신 #{id} — {agent} 앞. 'pilo task {id}' 의 answer 를 읽고 이어서 진행.",
  "wake.nudge": "[pilo:nudge] 작업 #{id} — {agent} 앞. 아직 열려 있고 보고가 없음. 끝났으면 'pilo done {id}' 로 기록.",
  "wake.result": "[pilo:result] 결과 도착 #{id} — 'pilo inbox {id}' 로 취합 후 'pilo reply {id}'.",
  "wake.rules": "[pilo:rules] 지시문이 갱신됐다. {file} 의 pilo:begin ~ pilo:end 블록을 읽고 지금부터 그대로 동작해.",
  "wake.check": "[pilo] {agent} 확인 요청",

  "dash.tab.work": "Work",
  "dash.tab.work.desc": "트리 · 대화 · 입력",
  "dash.tab.overview": "Overview",
  "dash.tab.overview.desc": "agent 상태 · 최근 task · 런타임",
  "dash.tab.agents": "Agents",
  "dash.tab.agents.desc": "조직도와 agent 등록",
  "dash.tab.inbox": "Inbox",
  "dash.tab.inbox.desc": "사용자 입력과 처리 경로",
  "dash.tab.events": "Events",
  "dash.tab.events.desc": "pm_result · final_reply · event 원문",
  "dash.tab.artifacts": "Artifacts",
  "dash.tab.artifacts.desc": "agent가 만든 파일과 변경 내용",
  "dash.tab.projects": "Projects",
  "dash.tab.projects.desc": "프로젝트 · 경로 · 담당 PM",
  "dash.tab.schedules": "Schedules",
  "dash.tab.schedules.desc": "정기 작업 · 언제 무엇이 도는지",
  "dash.tab.commands": "Commands",
  "dash.tab.commands.desc": "TUI와 CLI에서 쓰는 명령",
  "dash.tab.settings": "Settings",
  "dash.tab.settings.desc": "알림 · 토큰 표기 · 보관 기간",
  "dash.tab.system": "System",
  "dash.tab.system.desc": "server · wake · dashboard 상태와 경로",

  // 데스크 화면. 나머지 대시보드 문구는 시안의 영어를 그대로 두었고 아직 전환되지 않음.
  "desk.rail.work": "작업",
  "desk.rail.agents": "에이전트",
  "desk.rail.inbox": "요청",
  "desk.rail.schedules": "예약",
  "desk.rail.events": "기록",
  "desk.rail.artifacts": "산출물",
  "desk.rail.projects": "프로젝트",
  "desk.rail.commands": "명령",
  "desk.rail.settings": "설정",
  "desk.rail.system": "시스템",
  "desk.title.agents": "에이전트",
  "desk.title.inbox": "요청",
  "desk.title.schedules": "예약",
  "desk.title.events": "기록",
  "desk.title.artifacts": "산출물",
  "desk.title.projects": "프로젝트",
  "desk.title.commands": "명령",
  "desk.title.settings": "설정",
  "desk.title.system": "시스템",
  "desk.act.addAgent": "에이전트 추가",
  "desk.act.resendRules": "지시문 다시 보내기",
  "desk.act.newSchedule": "예약 추가",
  "desk.act.newProject": "프로젝트 추가",
  "desk.act.save": "저장",
  "desk.act.remove": "삭제",
  "desk.act.cancel": "취소",
  "desk.act.wake": "깨우기",
  "desk.act.bind": "다시 연결",
  "desk.act.copy": "복사",
  "desk.act.close": "닫기",
  "desk.lbl.byAgent": "에이전트별",
  "desk.lbl.requests": "요청",
  "desk.lbl.handling": "처리 경로",
  "desk.lbl.everyAgent": "전체",
  "desk.lbl.files": "파일",
  "desk.lbl.eventLog": "기록",
  "desk.lbl.recentRuns": "최근 실행",
  "desk.lbl.appearance": "화면",
  "desk.lbl.services": "서비스",
  "desk.lbl.sessions": "herdr 세션",
  "desk.lbl.tokensToday": "오늘 토큰",
  "desk.lbl.wakeFailures": "wake 실패",
  "desk.lbl.paths": "경로",
  "desk.lbl.log": "로그",
  "desk.lbl.language": "언어",
  "desk.lbl.theme": "테마",
  "desk.lbl.nothingHere": "없음",
  "desk.lbl.clearFilter": "필터 지우기",
  "desk.composer": "무엇을 할지 적으세요",
  "desk.composer.hint": "ENTER 로 보냄",
  "desk.follow.ask": "이어 묻기",
  "desk.follow.chip": "in-{id} 에 이어 묻는 중",
  "desk.follow.cancel": "이어 묻기 취소",
  "desk.follow.prefix": "in-{id} 이어서 — "
};

export const LANGS = { en: EN, ko: KO };
// The dashboard imports this file too, where there is no process to read.
const wanted = typeof process === "undefined" ? "" : process.env.PILO_LANG || "";
export const lang = LANGS[wanted] ? wanted : "en";

// t("card.needsReplyMany", { count: 3 }). Unknown keys come back as the key
// itself, which is louder in a screenshot than an empty string.
export function t(key, vars = {}) {
  const table = LANGS[lang] || EN;
  const line = table[key] ?? EN[key] ?? key;
  return String(line).replace(/\{(\w+)\}/g, (_, name) => (vars[name] === undefined ? `{${name}}` : String(vars[name])));
}
